services:
  postgres:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
